### PR TITLE
Store credit cancel

### PR DESCRIPTION
**Pull request by gmacdougall**
Improve store credit cancellation

This brings in two PR's from Solidus which improve the flow of cancelling orders with store credit payments:

https://github.com/solidusio/solidus/pull/1292
https://github.com/solidusio/solidus/pull/1603

### CODE REVIEW

**Comment by bbuchalter** [comment]
When I cancel an order with captured store payments, I see my store credit payment is voided, but when I view the ledger history, I see no originator for the reversing entry.
screen shot 2016-11-22 at 8 43 46 pm

**Comment by gmacdougall** [comment]
I added the originator in to that such that it gets sent in to the ledger.

**Comment by bbuchalter** [comment]
When I complete an order using only store credit, refund the full amount of the store credit and then cancel the order I get this error: https://app.bugsnag.com/tommy-john-inc/tommyjohn-dot-com/errors/5835a32107b7add195afef27?filters%5Bevent.since%5D%5B%5D=30d&filters%5Berror.status%5D%5B%5D=open

**Comment by gmacdougall** [comment]
I have updated this to correctly work when the full amount is already refunded.

**Review by stewart — APPROVED** [review]

**Pull request merged**
